openapi: 3.0.0
info:
  title: Coligo API
  version: 1.0.0
  description: API for managing users, courses, quizzes, and announcements

paths:
  /api/v1/announcements:
    get:
      summary: Get all announcements
      tags:
        - Announcements
      parameters:
        - in: query
          name: page
          required: false
          schema:
            type: integer
          description: Page number for pagination (default: 0)
        - in: query
          name: pageSize
          required: false
          schema:
            type: integer
          description: Number of items per page (default: 10)
      responses:
        200:
          description: List of announcements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Announcement"
    post:
      summary: Create a new announcement
      tags:
        - Announcements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Announcement"
      responses:
        201:
          description: Announcement created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Announcement"

  /api/v1/announcements/{id}:
    get:
      summary: Get a single announcement by ID
      tags:
        - Announcements
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the announcement
      responses:
        200:
          description: Announcement details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Announcement"
        404:
          description: Announcement not found

    put:
      summary: Update an announcement by ID
      tags:
        - Announcements
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the announcement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Announcement"
      responses:
        200:
          description: Announcement updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Announcement"
        404:
          description: Announcement not found

    delete:
      summary: Delete an announcement by ID
      tags:
        - Announcements
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the announcement
      responses:
        204:
          description: Announcement deleted successfully
        404:
          description: Announcement not found

components:
  schemas:
    Announcement:
      type: object
      required:
        - title
        - content
      properties:
        id:
          type: string
          description: The auto-generated ID of the announcement
        title:
          type: string
          description: The title of the announcement
        creatorId:
          type: string
          description: The ID of the user who created the announcement
        content:
          type: string
          description: The content of the announcement
        createdAt:
          type: string
          format: date-time
          description: The timestamp when the announcement was created
        updatedAt:
          type: string
          format: date-time
          description: The timestamp when the announcement was last updated
      example:
        id: "635ad35b091234c9b12345aa"
        title: "Important Update"
        creatorId: "635ad35b091234c9b12345bb"
        content: "This is an important update for all users."
        createdAt: "2024-11-16T08:55:00Z"
        updatedAt: "2024-11-16T09:00:00Z"
